### ISSUE TITLE
change text: "React App"

### ISSUE THREAD

**Issue by borbota** [k-monitor/parliamentary_debates_open#16]
seen after copy-pasting the link to a closed group:
![Uploading Screenshot from 2018-05-21 17-55-38.png…]()

**Comment by kantord** [comment]
The image seems to be broken.

**Comment by borbota** [comment]
sorryka ![screenshot from 2018-05-21 17-55-38](https://user-images.githubusercontent.com/9154908/40319426-6bc954a2-5d28-11e8-9c6a-7c22297a980b.png)
