### ISSUE TITLE
change color of calendar arrow

### ISSUE THREAD

**Issue by borbota** [k-monitor/parliamentary_debates_open#28]
![naptar](https://user-images.githubusercontent.com/9154908/52122156-4501cc00-2622-11e9-96a1-05b527ce85a9.jpg)
currently it is not visible

**Comment by kantord** [comment]
this component doesn't work after updating to react 4, so it's been replaced with a temporary solution. this should be the final solution https://github.com/k-monitor/parliamentary_debates_open/issues/37
