### ISSUE TITLE
The query should be represented in the URL as well

### ISSUE THREAD

**Issue by andraskalman** [k-monitor/parliamentary_debates_open#3]
This way the users can easily share search results.

Use a GET query parameter or a path param, e.g.:
 https://k-monitor.github.io/parliamentary_debates_open?q=kósa or https://k-monitor.github.io/parliamentary_debates_open/kósa

**Comment by kantord** [comment]
Resolving this requires client-side routing, which is not officially supported by GitHub pages, although it is possible to do by abusing a 404 page. Furthermore, it requires a bigger change in how querying works.

In view of the above, do we consider this a high-priority issue?

**Comment by andraskalman** [comment]
I think we should fix it, currently the users can not share the search results, bookmark links to reproduce the searches and it is difficult to link the result page as a reference as well.

**Comment by kantord** [comment]
Would we want to represent the keyword only, or the entire query configuration?

**Comment by andraskalman** [comment]
The filters should be represented as well in the url. The result page should be reproducible.

**Comment by kantord** [comment]
fixed
