### ISSUE TITLE
indicate search term somewhere

### ISSUE THREAD

**Issue by borbota** [k-monitor/parliamentary_debates_open#43]
I have made a search, the site refreshed, I have ended up with [this url](https://k-monitor.github.io/parliamentary_debates_open/?hitOpen=null&term=korrupci%C3%B3), but could not see the search term anywhere, except for in the URL.
![screenshot from 2019-02-05 14-18-50](https://user-images.githubusercontent.com/9154908/52275959-3e8c9080-2951-11e9-96e7-f14dd95eec15.png)

A solution could be to add the word to the part where the number of results is indicated:
{insert search term here} – 5184 találat:

**Comment by kantord** [comment]
related to https://github.com/k-monitor/parliamentary_debates_open/issues/41
