### ISSUE TITLE
staging 80: after deleting search text site jumps to the page with cards

### ISSUE THREAD

**Issue by borbota** [k-monitor/parliamentary_debates_open#85]
On https://staging-80-parldata.surge.sh, if after typing in some text for the search box and I change my mind and delete it, the site jumps back to the page with the cards. As a user I found this behaviour strange, but let's discuss.

**Comment by borbota** [comment]
this is not the case with staging 82

**Comment by kantord** [comment]
what is staging 80? We only have one open pull request, #82
